FROM amazonlinux:2 as amz-linux
VOLUME /var/lib/docker
ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime


FROM amz-linux as python-layer
RUN yum -y update
RUN yum -y groupinstall "Development Tools"
RUN yum install -y wget dos2unix libffi-devel bzip2-devel

#install openssl
ARG OPENSSL_VERSION=1.1.1q
RUN cd $(mktemp -d) && \
wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
tar -xf openssl-${OPENSSL_VERSION}.tar.gz && \
cd openssl-${OPENSSL_VERSION} && \
./config --prefix=/var/lang && \
make -j$(nproc) && \
make install

# install python
ARG PYTHON_VERSION=3.11.0
RUN cd $(mktemp -d) && \
wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz && \
tar -xf Python-${PYTHON_VERSION}.tgz && \
cd Python-${PYTHON_VERSION} && \
./configure --with-openssl=/var/lang --with-ensurepip=upgrade --enable-shared --with-lto=full --prefix=/var/lang --enable-optimizations  --with-system-ffi --with-computed-gotos --enable-loadable-sqlite-extensions && \
make -j$(nproc) && \
make install

# Add extra files
WORKDIR /

COPY lambda-entrypoint.sh .
RUN dos2unix lambda-entrypoint.sh
RUN chmod +x lambda-entrypoint.sh

WORKDIR /var/runtime
COPY runtime-release .
RUN dos2unix runtime-release
RUN chmod 644 runtime-release

COPY bootstrap.py .
RUN dos2unix bootstrap.py
RUN chmod 644 bootstrap.py

COPY bootstrap .
RUN dos2unix bootstrap
RUN chmod +x bootstrap

COPY layer_bootstrap .
RUN dos2unix layer_bootstrap
RUN chmod +x layer_bootstrap

FROM amz-linux as base-layer

WORKDIR /var/task
COPY --from=python-layer /var/runtime /var/runtime
COPY --from=python-layer /var/lang /var/lang
COPY --from=python-layer /lambda-entrypoint.sh /lambda-entrypoint.sh

RUN ln -s python3 /var/lang/bin/python && \
ln -s python3-config /var/lang/bin/python-config && \
ln -s pydoc3 /var/lang/bin/pydoc && \
ln -s pip3 /var/lang/bin/pip && \
# install lambda runtime interface client for python
pip install --no-cache-dir --target /var/runtime awslambdaric boto3

ENTRYPOINT [ "/lambda-entrypoint.sh" ]